name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        package: [parser, react]
        include:
          - package: parser
            path: search-input-query-parser
          - package: react
            path: search-input-query-react

    defaults:
      run:
        working-directory: ${{ matrix.path }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.path }}/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      if: matrix.package != 'demo'
      run: npm test

    - name: TypeScript check
      run: npm run type-check